### ISSUE TITLE
How to use detection of silence?

### ISSUE THREAD

**Issue by FriedaSmith** [debmalya/JavaVAD#2]
Hello. I didn't find out how it does detection of silence. Do you have a document on how it is used?

**Comment by debmalya** [comment]
- Listening from AudioInputStream. 

- Get available bytes

- In case of silence all the values are equals to 0. This is the observation. Still I am testing this one. 

- You can try to run file SilenceDetector.java

**Comment by FriedaSmith** [comment]
Thank you very much.
